spring.application.name=SecureJobPortalApplication

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/SecureJobApplication

# Username & Password
spring.datasource.username=root
spring.datasource.password=software@muet19

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

